#!/bin/bash
#SBATCH --job-name=avt_distill_pretrained_roberta_wt10_fold_1_lr_1e7.job
#SBATCH --output=/home/taggarwal/AVT-main/avt_distill_pretrained_roberta_wt10_fold_1_lr_1e7_out.txt
#SBATCH --error=/home/taggarwal/AVT-main/avt_distill_pretrained_roberta_wt10_fold_1_lr_1e7_err.txt
#SBATCH --time=3-10:00
#SBATCH --mem=50000
#SBATCH --gres=gpu

# Test nvidia-smi
nvidia-smi

# Test Python conda environment
source /home/taggarwal/anaconda3/etc/profile.d/conda.sh
conda activate avt

cd /home/taggarwal/AVT-main
# Run the experiment, storing in local_f1_roberta
python3 -X faulthandler launch.py -c expts/13_50s_avt.txt -g