#!/bin/bash
#SBATCH --job-name=avt_base_feat_egtea_test.job
#SBATCH --output=/home/taggarwal/AVT-main/expout/avt_egtea_notpretrained_distillbert_kldiv_16may_wt150_t10_out.txt
#SBATCH --error=/home/taggarwal/AVT-main/expout/avt_egtea_notpretrained_distillbert_kldiv_16may_wt150_t10_err.txt
#SBATCH --time=3-10:00
#SBATCH --mem=50000
#SBATCH --gres=gpu

# Test nvidia-smi
nvidia-smi

# Test Python conda environment
source /home/taggarwal/anaconda3/etc/profile.d/conda.sh
conda activate avt

cd /home/taggarwal/AVT-main
# Run the experiment, storing in local_egtea_notpretrained_distillbert_kldiv_16may_wt150_t10
python3 -X faulthandler launch.py -c expts/12_egtea_avt.txt -g